name: Android Espresso CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: set up JDK 1.8
      uses: actions/setup-java@1
      with:
        java-version: 1.8
    
    - name: Build mobile app with Gradle
      run: |
        cd MobileEnd
        ./gradlew build
    
  tests:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: |
          cd MobileEnd
          ./gradlew connectedCheck
